### ISSUE TITLE
MDD（Microdiode Electronics） 2N7002 and KOA Speer Elec RK73H2ATTD9101F alternative components

### ISSUE THREAD

**Issue by ngswk** [tzarc/djinn#10]
MDD（Microdiode Electronics） 2N7002 listed in the Rev2a BOM is now discontinued, is there a list of alternative components that can be used in its place for the build?

Also, the following component seems to be out of stock everywhere: KOA Speer Elec RK73H2ATTD9101F
are there alternative components for this as well?

**Comment by tzarc** [comment]
Both are jellybean parts -- anything with the same name will match the 2N7002, and anything with the same value and package size will match the RK73H2ATTD9101F.

**Comment by ngswk** [comment]
okay I see, so anything matching the following should work then:

9.1k 1% | 0805 | RK73H2ATTD9101F
- | SOT-23-3 | 2N7002

Many thanks for your help!

**Comment by tzarc** [comment]
Yep, just make sure the pinout on the replacement 2N7002 matches -- sometimes manufacturers reorder them.

**Comment by ngswk** [comment]
do the below get your stamp of approval?

https://lcsc.com/product-detail/MOSFETs_span-style-background-color-ff0-Jiangsu-span-Changjing-Electronics-Technology-Co-Ltd-2N7002_C8545.html

https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount_TyoHM-RMC08059-1K1-N_C325830.html

**Comment by tzarc** [comment]
Yep, they look fine to me.

**Comment by ngswk** [comment]
Awesome!! Now all i need is to find 2 MCUs once they are back in stock!

Many thanks for all of your help once again!
