### ISSUE TITLE
Printing pcb

### ISSUE THREAD

**Issue by MysticNynja** [tzarc/djinn#4]
I found the Gerber files, how do you get left and right? Are they double sided?

**Comment by tzarc** [comment]
Yes. Completely reversible.

I'd recommend not getting PCBs until you've sourced the other parts -- STM32G474's are basically unobtainium at the moment.

**Comment by pinball83** [comment]
@tzarc Could add bom file in XLS,XLSX,CSV format?

**Comment by MysticNynja** [comment]
So I just ordered some from mouser, and their lead time is September of 2023..... so I canceled them and looking for this unicorn chip now...
