### ISSUE TITLE
Switch support

### ISSUE THREAD

**Issue by Daegalus** [tzarc/djinn#5]
Wanted to ask if this supports multiple switch types like it seems it does? Primarily wanted to know if it supports Kailh Chocs?

**Comment by tzarc** [comment]
No choc support I'm afraid. It's only capable of using MX hotswap sockets.

But... you could always modify the footprint if you're keen on using them instead.

**Comment by Daegalus** [comment]
My concern with that is the leads and connections if i were to change the footprint if it would still be properly connected, im not well versed in kicad, Ill give it a shot though. I do low profile keyboards so Kailh Choc support is needed, but so few are more than 58 keys that when I see a great keyboard like this, i always have to ask.
