### ISSUE TITLE
JLCPCB

### ISSUE THREAD

**Issue by ricrug** [tzarc/djinn#6]
Trying to upload the Main gerber to jlcpcb the system reports errors and does not complete the process:
- The processing has timed out
- Can not identify the board outline
- Djinn-PTH.drl(null):Unrecognized Gerber file

What printing service did you used?

**Comment by tzarc** [comment]
JLCPCB is fine -- their website seems to choke on the design but if you put the dimensions in manually they work it out.
I used JLCPCB fine with the committed zip files, I'm not sure why yours aren't compatible.

**Comment by erniemaster** [comment]
Can confirm!
Ordered the PCB's 3 days ago and got the same error message you described. Entering the dimension of the base-PCB worked and all three layouts are now right on the way.

Other manufactures have no problems with the provided Gerber-Files, so it's just an error of JLCPCB's online viewer.

(P.S.: the STM-controller used for this keyboard is actually available at Newark.)

**Comment by ricrug** [comment]
> Can confirm! Ordered the PCB's 3 days ago and got the same error message you described. Entering the dimension of the base-PCB worked and all three layouts are now right on the way.
> 
> Other manufactures have no problems with the provided Gerber-Files, so it's just an error of JLCPCB's online viewer.
> 
> (P.S.: the STM-controller used for this keyboard is actually available at Newark.)

Did you also buy the stencils or the SMT assembly?

**Comment by erniemaster** [comment]
I only bought the PCB's, since there were some parts not available from LCSC.
With some research its actual possible to find every part needed for the keyboard, but you have to place orders around the globe.

**Comment by ricrug** [comment]
I think the replies are exhaustive!
Thank you @tzarc and @erniemaster
