### ISSUE TITLE
MCU purchasing concerns

### ISSUE THREAD

**Issue by ricrug** [tzarc/djinn#7]
The STM32G474RET6 is not easy to find in distribution.
Are there any ideas on how to get it? Is there anything to replace it with? :upside_down_face:

**Comment by tzarc** [comment]
The only pin-compatible MCUs are:
* STM32G473RET6
* STM32G483RET6
* ~~STM32G474RET6~~
* STM32G484RET6

The design is reliant on the G4xx USBPD peripheral so it'd require a large amount of rework to replace it with something from another family.

I've basically told everyone to get parts before boards -- there's no need to make the boards if you can't source the components.
