### ISSUE TITLE
can u help me

### ISSUE THREAD

**Issue by TOMMYBIU** [tzarc/djinn#8]
Hello, can you give out a video on how to import qmk files to this keyboard, in yutobe. This keyboard looks very interesting, but I have just come into contact with homemade keyboards and I still don’t know much about it.

**Comment by tzarc** [comment]
I'm sorry, I don't do YouTube videos.
If you want to learn QMK, your best bet is to check out the [QMK tutorial](https://docs.qmk.fm/#/newbs).

When you're familiar with that, you'll need to add the Djinn firmware repository to QMK:
```sh
cd ~/qmk_firmware
git remote add tzarc https://github.com/tzarc/qmk_firmware.git
```
....and then swap to the branch:
```sh
cd ~/qmk_firmware
git fetch tzarc
git checkout -b my-djinn tzarc/djinn
```

You can then build accordingly.
